databases:
  - name: musicsearch_DB
    databaseName: musicsearch_db
    user: musicsearch
    region: singapore

services:
  - type: web
    name: musicsearch_DB
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: musicsearch_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

